name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        rust: [stable, nightly]

    steps:
    - name: Set up a Rust toolchain
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: cargo build --locked

    - name: Build release
      run: cargo build --release --locked

    - name: Strip release
      run: strip target/release/zswap-cli

    - name: Run tests
      run: cargo test --verbose

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: zswap-cli_rust-${{ matrix.rust }}-${{ matrix.os }}
        path: target/release/zswap-cli
